# Testing image for aurelo-data-engine
# Builds on top of the dev image you build from your fork

# IMPORTANT: make sure you've already built your main image, e.g.:
#   docker build -t aurelo-data-engine:dev -f Dockerfile .
# or via: docker-compose build app

FROM aurelo-data-engine:dev

USER 0

# Copy and install test dependencies for this project
COPY --chown=1001:0 pyproject.toml .
COPY --chown=1001:0 poetry.lock .

RUN --mount=type=cache,target=$PIP_CACHE_DIR,uid=1001,gid=0 \
    poetry check --lock && POETRY_VIRTUALENVS_CREATE=false poetry install --only test

USER 1001

