version: "3.9"

services:
  db:
    image: postgres:15
    hostname: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.development   # dev Dockerfile we wrote
    image: aurelo-data-engine:dev          # <-- YOUR image name
    container_name: aurelo-data-engine-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DJANGO_DB: default
      POSTGRE_NAME: postgres
      POSTGRE_USER: postgres
      POSTGRE_PASSWORD: postgres
      POSTGRE_PORT: 5432
      POSTGRE_HOST: db
      JSON_LOG: 1
      PORT: 8080
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      DEBUG: "1"
      ALLOWED_HOSTS: "*"
    volumes:
      - ./:/label-studio
      - ./mydata:/label-studio/data:rw
    working_dir: /label-studio
    ports:
      - "8080:8080"

volumes:
  pgdata:
